create extension if not exists pgcrypto;
create table if not exists airports(id uuid primary key default gen_random_uuid(),iata text unique not null,name text not null,country text,city text,created_at timestamptz default now());
create table if not exists terminals(id uuid primary key default gen_random_uuid(),airport_id uuid not null references airports(id) on delete cascade,name text not null,created_at timestamptz default now(),unique(airport_id,name));
create table if not exists places(id uuid primary key default gen_random_uuid(),terminal_id uuid not null references terminals(id) on delete cascade,title text not null,area text,can_lie boolean default false,quiet smallint default 3 check(quiet between 1 and 5),dark smallint default 3 check(dark between 1 and 5),comfort smallint default 3 check(comfort between 1 and 5),power boolean default false,toilet_distance_m integer,shower_nearby boolean default false,latitude double precision,longitude double precision,verified boolean default false,created_at timestamptz default now());
create table if not exists ratings(id uuid primary key default gen_random_uuid(),place_id uuid not null references places(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,comfort smallint not null check(comfort between 1 and 5),noise smallint not null check(noise between 1 and 5),light smallint not null check(light between 1 and 5),temperature smallint not null check(temperature between 1 and 5),safety smallint not null check(safety between 1 and 5),privacy smallint not null check(privacy between 1 and 5),amenities smallint not null check(amenities between 1 and 5),cleanliness smallint not null check(cleanliness between 1 and 5),comment text,created_at timestamptz default now());
create table if not exists place_photos(id uuid primary key default gen_random_uuid(),place_id uuid not null references places(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,storage_path text not null,created_at timestamptz default now());
create table if not exists profiles(user_id uuid primary key references auth.users(id) on delete cascade,display_name text not null,created_at timestamptz default now());
insert into airports(iata,name,country,city) values('AUH','Zayed International Airport','United Arab Emirates','Abu Dhabi') on conflict(iata) do nothing;
insert into terminals(airport_id,name) select id,'Terminal A' from airports where iata='AUH' on conflict(airport_id,name) do nothing;
insert into places(terminal_id,title,area,can_lie,quiet,dark,comfort,power,toilet_distance_m,shower_nearby,verified) select t.id,'Диванчики у Gate D','Gate series D',true,4,3,5,true,35,true,true from terminals t join airports a on a.id=t.airport_id where a.iata='AUH' and t.name='Terminal A' and not exists(select 1 from places p where p.terminal_id=t.id and p.title='Диванчики у Gate D');
insert into places(terminal_id,title,area,can_lie,quiet,dark,comfort,power,toilet_distance_m,shower_nearby,verified) select t.id,'Широкие лавочки у Burger King','Food Court',true,3,3,4,false,25,true,true from terminals t join airports a on a.id=t.airport_id where a.iata='AUH' and t.name='Terminal A' and not exists(select 1 from places p where p.terminal_id=t.id and p.title='Широкие лавочки у Burger King');

alter table airports enable row level security; alter table terminals enable row level security; alter table places enable row level security; alter table ratings enable row level security; alter table place_photos enable row level security; alter table profiles enable row level security;
drop policy if exists "public read airports" on airports; create policy "public read airports" on airports for select using(true);
drop policy if exists "public read terminals" on terminals; create policy "public read terminals" on terminals for select using(true);
drop policy if exists "public read places" on places; create policy "public read places" on places for select using(true);
drop policy if exists "authenticated create places" on places; create policy "authenticated create places" on places for insert to authenticated with check(true);
drop policy if exists "public read ratings" on ratings; create policy "public read ratings" on ratings for select using(true);
drop policy if exists "authenticated create ratings" on ratings; create policy "authenticated create ratings" on ratings for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists "public read photos" on place_photos; create policy "public read photos" on place_photos for select using(true);
drop policy if exists "authenticated create photos" on place_photos; create policy "authenticated create photos" on place_photos for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists "public read profiles" on profiles; create policy "public read profiles" on profiles for select using(true);
drop policy if exists "users manage own profile" on profiles; create policy "users manage own profile" on profiles for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);

insert into storage.buckets(id,name,public) values('place-photos','place-photos',true) on conflict(id) do update set public=true;
drop policy if exists "public read place photos" on storage.objects; create policy "public read place photos" on storage.objects for select using(bucket_id='place-photos');
drop policy if exists "authenticated upload place photos" on storage.objects; create policy "authenticated upload place photos" on storage.objects for insert to authenticated with check(bucket_id='place-photos');
